apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
spec:
  ports:
  - name: app
    port: 7990
    protocol: TCP
    targetPort: 7990
  selector:
    workload.user.cattle.io/workloadselector: deployment-{{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ssh
spec:
  ports:
  - name: ssh
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 7999
  - name: sshdefault
    port: 7999
    protocol: TCP
    targetPort: 7999
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    workload.user.cattle.io/workloadselector: deployment-{{ .Release.Name }}
  sessionAffinity: None
  type: {{ .Values.service.type }}