# Default values for jira-software.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.k8.network/library/atlassian-jira-software
  tag: latest
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  pullSecret: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  ## Set to true to enable ingress record generation
  enabled: false
  ## Set this to true in order to add the corresponding annotations for cert-manager
  certManager: false
  ## Ingress annotations done as key:value pairs
  ## If certManager is set to true, annotation kubernetes.io/tls-acme: "true" will automatically be set
  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
  ## The list of hostnames to be covered with this ingress record.
  ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  host:
    name: jira.local
    path: /
    ## Set this to true in order to enable TLS on the ingress record
    tls: false
    ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
    tlsSecret: jira.local-tls

persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 20Gi

memory:
  min: 512m
  max: 2048m