apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
  - name: jira
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-{{ .Release.Name }}
  sessionAffinity: None
  type: {{ .Values.service.type }}