apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-{{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-{{ .Release.Name }}
    spec:
      {{if .Values.persistence.enabled}}
      volumes:
        - name: {{ .Release.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data-claim
      {{end}}
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: app
        ports:
        - containerPort: {{ .Values.service.port }}
          name: {{ .Values.service.port }}tcp02
          protocol: TCP
        env:

        {{- if .Values.ingress.enabled }}
        - name: ATL_PROXY_NAME
          value: {{ .Values.ingress.host.name }}
        - name: ATL_PROXY_PORT
          value: {{ if .Values.ingress.host.tls }}"443"{{ else }}"80"{{ end }}
        - name: ATL_TOMCAT_SCHEME
          value: {{ if .Values.ingress.host.tls }}"https"{{ else }}"http"{{ end }}
        - name: ATL_TOMCAT_SECURE
          value: {{ if .Values.ingress.host.tls }}"true"{{ else }}"false"{{ end }}
        {{- end }}

        - name: JVM_MINIMUM_MEMORY
          value: {{ .Values.memory.min }}
        - name: JVM_MAXIMUM_MEMORY
          value: {{ .Values.memory.max }}
        - name: CATALINA_CONTEXT_PATH
          value: {{ .Values.ingress.host.path }}
    
        {{- if .Values.postgres.enabled }}
        - name: ATL_JDBC_URL
          value: "jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port}}/{{ .Values.postgres.database }}"
        - name: ATL_JDBC_USER
          value: {{.Values.postgres.username }}
        - name: ATL_JDBC_PASSWORD
          value: {{.Values.postgres.password }}
        - name: ATL_DB_DRIVER
          value: "org.postgresql.Driver"
        - name: ATL_DB_TYPE
          value: "postgres72"
        {{- end }}
        resources: {}
        volumeMounts:
        - mountPath: /var/atlassian/application-data/crowd
          name: {{ .Release.Name }}-data
      {{if .Values.image.pullSecret}}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{end}}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30