{{if .Values.ingress.enabled}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    {{if .Values.ingress.certManager}}
    kubernetes.io/tls-acme: "true"
    {{end}}
spec:
  rules:
  - host: {{ .Values.ingress.host.name }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}
          servicePort: {{ .Values.service.port }}
        path: {{ .Values.ingress.host.path }}
  {{if .Values.ingress.host.tls}}
  tls:
  - hosts:
    - {{ .Values.ingress.host.name }}
    secretName: {{ .Values.ingress.host.tlsSecret }}
  {{end}}
{{end}}