{{ if .Values.persistence.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-data-claim
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{ if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{ end }}
{{ end }}